/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDashboardRequestsRouteImport } from './routes/_authenticated/dashboard.requests'
import { Route as AuthenticatedDashboardProfileRouteImport } from './routes/_authenticated/dashboard.profile'
import { Route as AuthenticatedDashboardCoursesRouteImport } from './routes/_authenticated/dashboard.courses'
import { Route as AuthenticatedDashboardCertificatesRouteImport } from './routes/_authenticated/dashboard.certificates'
import { Route as AuthenticatedDashboardAssignmentsRouteImport } from './routes/_authenticated/dashboard.assignments'
import { Route as AuthenticatedDashboardStudentIndexRouteImport } from './routes/_authenticated/dashboard.student.index'
import { Route as AuthenticatedDashboardInstructorIndexRouteImport } from './routes/_authenticated/dashboard.instructor.index'
import { Route as AuthenticatedDashboardClientIndexRouteImport } from './routes/_authenticated/dashboard.client/index'
import { Route as AuthenticatedDashboardAdminIndexRouteImport } from './routes/_authenticated/dashboard.admin.index'
import { Route as AuthenticatedDashboardStudentProfileRouteImport } from './routes/_authenticated/dashboard.student.profile'
import { Route as AuthenticatedDashboardStudentMessagesRouteImport } from './routes/_authenticated/dashboard.student.messages'
import { Route as AuthenticatedDashboardStudentCoursesRouteImport } from './routes/_authenticated/dashboard.student.courses'
import { Route as AuthenticatedDashboardStudentCertificatesRouteImport } from './routes/_authenticated/dashboard.student.certificates'
import { Route as AuthenticatedDashboardStudentAttendanceRouteImport } from './routes/_authenticated/dashboard.student.attendance'
import { Route as AuthenticatedDashboardStudentAssignmentsRouteImport } from './routes/_authenticated/dashboard.student.assignments'
import { Route as AuthenticatedDashboardStudentAnnouncementsRouteImport } from './routes/_authenticated/dashboard.student.announcements'
import { Route as AuthenticatedDashboardInstructorMessagesRouteImport } from './routes/_authenticated/dashboard.instructor.messages'
import { Route as AuthenticatedDashboardInstructorCoursesRouteImport } from './routes/_authenticated/dashboard.instructor.courses'
import { Route as AuthenticatedDashboardInstructorAttendanceRouteImport } from './routes/_authenticated/dashboard.instructor.attendance'
import { Route as AuthenticatedDashboardInstructorAnnouncementsRouteImport } from './routes/_authenticated/dashboard.instructor.announcements'
import { Route as AuthenticatedDashboardClientRequestsRouteImport } from './routes/_authenticated/dashboard.client/requests'
import { Route as AuthenticatedDashboardClientProjectsRouteImport } from './routes/_authenticated/dashboard.client/projects'
import { Route as AuthenticatedDashboardClientProfileRouteImport } from './routes/_authenticated/dashboard.client/profile'
import { Route as AuthenticatedDashboardClientMessagesRouteImport } from './routes/_authenticated/dashboard.client/messages'
import { Route as AuthenticatedDashboardClientInvoicesRouteImport } from './routes/_authenticated/dashboard.client/invoices'
import { Route as AuthenticatedDashboardClientAnnouncementsRouteImport } from './routes/_authenticated/dashboard.client/announcements'
import { Route as AuthenticatedDashboardAdminUsersRouteImport } from './routes/_authenticated/dashboard.admin.users'
import { Route as AuthenticatedDashboardAdminStudentsRouteImport } from './routes/_authenticated/dashboard.admin.students'
import { Route as AuthenticatedDashboardAdminSettingsRouteImport } from './routes/_authenticated/dashboard.admin.settings'
import { Route as AuthenticatedDashboardAdminRequestsRouteImport } from './routes/_authenticated/dashboard.admin.requests'
import { Route as AuthenticatedDashboardAdminPaymentsRouteImport } from './routes/_authenticated/dashboard.admin.payments'
import { Route as AuthenticatedDashboardAdminMessagesRouteImport } from './routes/_authenticated/dashboard.admin.messages'
import { Route as AuthenticatedDashboardAdminCoursesRouteImport } from './routes/_authenticated/dashboard.admin.courses'
import { Route as AuthenticatedDashboardAdminAnnouncementsRouteImport } from './routes/_authenticated/dashboard.admin.announcements'
import { Route as AuthenticatedDashboardAdminAnalyticsRouteImport } from './routes/_authenticated/dashboard.admin.analytics'

const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRequestsRoute =
  AuthenticatedDashboardRequestsRouteImport.update({
    id: '/requests',
    path: '/requests',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardProfileRoute =
  AuthenticatedDashboardProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardCoursesRoute =
  AuthenticatedDashboardCoursesRouteImport.update({
    id: '/courses',
    path: '/courses',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardCertificatesRoute =
  AuthenticatedDashboardCertificatesRouteImport.update({
    id: '/certificates',
    path: '/certificates',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAssignmentsRoute =
  AuthenticatedDashboardAssignmentsRouteImport.update({
    id: '/assignments',
    path: '/assignments',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardStudentIndexRoute =
  AuthenticatedDashboardStudentIndexRouteImport.update({
    id: '/student/',
    path: '/student/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardInstructorIndexRoute =
  AuthenticatedDashboardInstructorIndexRouteImport.update({
    id: '/instructor/',
    path: '/instructor/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardClientIndexRoute =
  AuthenticatedDashboardClientIndexRouteImport.update({
    id: '/client/',
    path: '/client/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAdminIndexRoute =
  AuthenticatedDashboardAdminIndexRouteImport.update({
    id: '/admin/',
    path: '/admin/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardStudentProfileRoute =
  AuthenticatedDashboardStudentProfileRouteImport.update({
    id: '/student/profile',
    path: '/student/profile',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardStudentMessagesRoute =
  AuthenticatedDashboardStudentMessagesRouteImport.update({
    id: '/student/messages',
    path: '/student/messages',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardStudentCoursesRoute =
  AuthenticatedDashboardStudentCoursesRouteImport.update({
    id: '/student/courses',
    path: '/student/courses',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardStudentCertificatesRoute =
  AuthenticatedDashboardStudentCertificatesRouteImport.update({
    id: '/student/certificates',
    path: '/student/certificates',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardStudentAttendanceRoute =
  AuthenticatedDashboardStudentAttendanceRouteImport.update({
    id: '/student/attendance',
    path: '/student/attendance',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardStudentAssignmentsRoute =
  AuthenticatedDashboardStudentAssignmentsRouteImport.update({
    id: '/student/assignments',
    path: '/student/assignments',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardStudentAnnouncementsRoute =
  AuthenticatedDashboardStudentAnnouncementsRouteImport.update({
    id: '/student/announcements',
    path: '/student/announcements',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardInstructorMessagesRoute =
  AuthenticatedDashboardInstructorMessagesRouteImport.update({
    id: '/instructor/messages',
    path: '/instructor/messages',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardInstructorCoursesRoute =
  AuthenticatedDashboardInstructorCoursesRouteImport.update({
    id: '/instructor/courses',
    path: '/instructor/courses',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardInstructorAttendanceRoute =
  AuthenticatedDashboardInstructorAttendanceRouteImport.update({
    id: '/instructor/attendance',
    path: '/instructor/attendance',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardInstructorAnnouncementsRoute =
  AuthenticatedDashboardInstructorAnnouncementsRouteImport.update({
    id: '/instructor/announcements',
    path: '/instructor/announcements',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardClientRequestsRoute =
  AuthenticatedDashboardClientRequestsRouteImport.update({
    id: '/client/requests',
    path: '/client/requests',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardClientProjectsRoute =
  AuthenticatedDashboardClientProjectsRouteImport.update({
    id: '/client/projects',
    path: '/client/projects',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardClientProfileRoute =
  AuthenticatedDashboardClientProfileRouteImport.update({
    id: '/client/profile',
    path: '/client/profile',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardClientMessagesRoute =
  AuthenticatedDashboardClientMessagesRouteImport.update({
    id: '/client/messages',
    path: '/client/messages',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardClientInvoicesRoute =
  AuthenticatedDashboardClientInvoicesRouteImport.update({
    id: '/client/invoices',
    path: '/client/invoices',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardClientAnnouncementsRoute =
  AuthenticatedDashboardClientAnnouncementsRouteImport.update({
    id: '/client/announcements',
    path: '/client/announcements',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAdminUsersRoute =
  AuthenticatedDashboardAdminUsersRouteImport.update({
    id: '/admin/users',
    path: '/admin/users',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAdminStudentsRoute =
  AuthenticatedDashboardAdminStudentsRouteImport.update({
    id: '/admin/students',
    path: '/admin/students',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAdminSettingsRoute =
  AuthenticatedDashboardAdminSettingsRouteImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAdminRequestsRoute =
  AuthenticatedDashboardAdminRequestsRouteImport.update({
    id: '/admin/requests',
    path: '/admin/requests',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAdminPaymentsRoute =
  AuthenticatedDashboardAdminPaymentsRouteImport.update({
    id: '/admin/payments',
    path: '/admin/payments',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAdminMessagesRoute =
  AuthenticatedDashboardAdminMessagesRouteImport.update({
    id: '/admin/messages',
    path: '/admin/messages',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAdminCoursesRoute =
  AuthenticatedDashboardAdminCoursesRouteImport.update({
    id: '/admin/courses',
    path: '/admin/courses',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAdminAnnouncementsRoute =
  AuthenticatedDashboardAdminAnnouncementsRouteImport.update({
    id: '/admin/announcements',
    path: '/admin/announcements',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAdminAnalyticsRoute =
  AuthenticatedDashboardAdminAnalyticsRouteImport.update({
    id: '/admin/analytics',
    path: '/admin/analytics',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solutions': typeof SolutionsRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/dashboard/assignments': typeof AuthenticatedDashboardAssignmentsRoute
  '/dashboard/certificates': typeof AuthenticatedDashboardCertificatesRoute
  '/dashboard/courses': typeof AuthenticatedDashboardCoursesRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/dashboard/requests': typeof AuthenticatedDashboardRequestsRoute
  '/dashboard/admin/analytics': typeof AuthenticatedDashboardAdminAnalyticsRoute
  '/dashboard/admin/announcements': typeof AuthenticatedDashboardAdminAnnouncementsRoute
  '/dashboard/admin/courses': typeof AuthenticatedDashboardAdminCoursesRoute
  '/dashboard/admin/messages': typeof AuthenticatedDashboardAdminMessagesRoute
  '/dashboard/admin/payments': typeof AuthenticatedDashboardAdminPaymentsRoute
  '/dashboard/admin/requests': typeof AuthenticatedDashboardAdminRequestsRoute
  '/dashboard/admin/settings': typeof AuthenticatedDashboardAdminSettingsRoute
  '/dashboard/admin/students': typeof AuthenticatedDashboardAdminStudentsRoute
  '/dashboard/admin/users': typeof AuthenticatedDashboardAdminUsersRoute
  '/dashboard/client/announcements': typeof AuthenticatedDashboardClientAnnouncementsRoute
  '/dashboard/client/invoices': typeof AuthenticatedDashboardClientInvoicesRoute
  '/dashboard/client/messages': typeof AuthenticatedDashboardClientMessagesRoute
  '/dashboard/client/profile': typeof AuthenticatedDashboardClientProfileRoute
  '/dashboard/client/projects': typeof AuthenticatedDashboardClientProjectsRoute
  '/dashboard/client/requests': typeof AuthenticatedDashboardClientRequestsRoute
  '/dashboard/instructor/announcements': typeof AuthenticatedDashboardInstructorAnnouncementsRoute
  '/dashboard/instructor/attendance': typeof AuthenticatedDashboardInstructorAttendanceRoute
  '/dashboard/instructor/courses': typeof AuthenticatedDashboardInstructorCoursesRoute
  '/dashboard/instructor/messages': typeof AuthenticatedDashboardInstructorMessagesRoute
  '/dashboard/student/announcements': typeof AuthenticatedDashboardStudentAnnouncementsRoute
  '/dashboard/student/assignments': typeof AuthenticatedDashboardStudentAssignmentsRoute
  '/dashboard/student/attendance': typeof AuthenticatedDashboardStudentAttendanceRoute
  '/dashboard/student/certificates': typeof AuthenticatedDashboardStudentCertificatesRoute
  '/dashboard/student/courses': typeof AuthenticatedDashboardStudentCoursesRoute
  '/dashboard/student/messages': typeof AuthenticatedDashboardStudentMessagesRoute
  '/dashboard/student/profile': typeof AuthenticatedDashboardStudentProfileRoute
  '/dashboard/admin/': typeof AuthenticatedDashboardAdminIndexRoute
  '/dashboard/client/': typeof AuthenticatedDashboardClientIndexRoute
  '/dashboard/instructor/': typeof AuthenticatedDashboardInstructorIndexRoute
  '/dashboard/student/': typeof AuthenticatedDashboardStudentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solutions': typeof SolutionsRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/dashboard/assignments': typeof AuthenticatedDashboardAssignmentsRoute
  '/dashboard/certificates': typeof AuthenticatedDashboardCertificatesRoute
  '/dashboard/courses': typeof AuthenticatedDashboardCoursesRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/dashboard/requests': typeof AuthenticatedDashboardRequestsRoute
  '/dashboard/admin/analytics': typeof AuthenticatedDashboardAdminAnalyticsRoute
  '/dashboard/admin/announcements': typeof AuthenticatedDashboardAdminAnnouncementsRoute
  '/dashboard/admin/courses': typeof AuthenticatedDashboardAdminCoursesRoute
  '/dashboard/admin/messages': typeof AuthenticatedDashboardAdminMessagesRoute
  '/dashboard/admin/payments': typeof AuthenticatedDashboardAdminPaymentsRoute
  '/dashboard/admin/requests': typeof AuthenticatedDashboardAdminRequestsRoute
  '/dashboard/admin/settings': typeof AuthenticatedDashboardAdminSettingsRoute
  '/dashboard/admin/students': typeof AuthenticatedDashboardAdminStudentsRoute
  '/dashboard/admin/users': typeof AuthenticatedDashboardAdminUsersRoute
  '/dashboard/client/announcements': typeof AuthenticatedDashboardClientAnnouncementsRoute
  '/dashboard/client/invoices': typeof AuthenticatedDashboardClientInvoicesRoute
  '/dashboard/client/messages': typeof AuthenticatedDashboardClientMessagesRoute
  '/dashboard/client/profile': typeof AuthenticatedDashboardClientProfileRoute
  '/dashboard/client/projects': typeof AuthenticatedDashboardClientProjectsRoute
  '/dashboard/client/requests': typeof AuthenticatedDashboardClientRequestsRoute
  '/dashboard/instructor/announcements': typeof AuthenticatedDashboardInstructorAnnouncementsRoute
  '/dashboard/instructor/attendance': typeof AuthenticatedDashboardInstructorAttendanceRoute
  '/dashboard/instructor/courses': typeof AuthenticatedDashboardInstructorCoursesRoute
  '/dashboard/instructor/messages': typeof AuthenticatedDashboardInstructorMessagesRoute
  '/dashboard/student/announcements': typeof AuthenticatedDashboardStudentAnnouncementsRoute
  '/dashboard/student/assignments': typeof AuthenticatedDashboardStudentAssignmentsRoute
  '/dashboard/student/attendance': typeof AuthenticatedDashboardStudentAttendanceRoute
  '/dashboard/student/certificates': typeof AuthenticatedDashboardStudentCertificatesRoute
  '/dashboard/student/courses': typeof AuthenticatedDashboardStudentCoursesRoute
  '/dashboard/student/messages': typeof AuthenticatedDashboardStudentMessagesRoute
  '/dashboard/student/profile': typeof AuthenticatedDashboardStudentProfileRoute
  '/dashboard/admin': typeof AuthenticatedDashboardAdminIndexRoute
  '/dashboard/client': typeof AuthenticatedDashboardClientIndexRoute
  '/dashboard/instructor': typeof AuthenticatedDashboardInstructorIndexRoute
  '/dashboard/student': typeof AuthenticatedDashboardStudentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solutions': typeof SolutionsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/_authenticated/dashboard/assignments': typeof AuthenticatedDashboardAssignmentsRoute
  '/_authenticated/dashboard/certificates': typeof AuthenticatedDashboardCertificatesRoute
  '/_authenticated/dashboard/courses': typeof AuthenticatedDashboardCoursesRoute
  '/_authenticated/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/_authenticated/dashboard/requests': typeof AuthenticatedDashboardRequestsRoute
  '/_authenticated/dashboard/admin/analytics': typeof AuthenticatedDashboardAdminAnalyticsRoute
  '/_authenticated/dashboard/admin/announcements': typeof AuthenticatedDashboardAdminAnnouncementsRoute
  '/_authenticated/dashboard/admin/courses': typeof AuthenticatedDashboardAdminCoursesRoute
  '/_authenticated/dashboard/admin/messages': typeof AuthenticatedDashboardAdminMessagesRoute
  '/_authenticated/dashboard/admin/payments': typeof AuthenticatedDashboardAdminPaymentsRoute
  '/_authenticated/dashboard/admin/requests': typeof AuthenticatedDashboardAdminRequestsRoute
  '/_authenticated/dashboard/admin/settings': typeof AuthenticatedDashboardAdminSettingsRoute
  '/_authenticated/dashboard/admin/students': typeof AuthenticatedDashboardAdminStudentsRoute
  '/_authenticated/dashboard/admin/users': typeof AuthenticatedDashboardAdminUsersRoute
  '/_authenticated/dashboard/client/announcements': typeof AuthenticatedDashboardClientAnnouncementsRoute
  '/_authenticated/dashboard/client/invoices': typeof AuthenticatedDashboardClientInvoicesRoute
  '/_authenticated/dashboard/client/messages': typeof AuthenticatedDashboardClientMessagesRoute
  '/_authenticated/dashboard/client/profile': typeof AuthenticatedDashboardClientProfileRoute
  '/_authenticated/dashboard/client/projects': typeof AuthenticatedDashboardClientProjectsRoute
  '/_authenticated/dashboard/client/requests': typeof AuthenticatedDashboardClientRequestsRoute
  '/_authenticated/dashboard/instructor/announcements': typeof AuthenticatedDashboardInstructorAnnouncementsRoute
  '/_authenticated/dashboard/instructor/attendance': typeof AuthenticatedDashboardInstructorAttendanceRoute
  '/_authenticated/dashboard/instructor/courses': typeof AuthenticatedDashboardInstructorCoursesRoute
  '/_authenticated/dashboard/instructor/messages': typeof AuthenticatedDashboardInstructorMessagesRoute
  '/_authenticated/dashboard/student/announcements': typeof AuthenticatedDashboardStudentAnnouncementsRoute
  '/_authenticated/dashboard/student/assignments': typeof AuthenticatedDashboardStudentAssignmentsRoute
  '/_authenticated/dashboard/student/attendance': typeof AuthenticatedDashboardStudentAttendanceRoute
  '/_authenticated/dashboard/student/certificates': typeof AuthenticatedDashboardStudentCertificatesRoute
  '/_authenticated/dashboard/student/courses': typeof AuthenticatedDashboardStudentCoursesRoute
  '/_authenticated/dashboard/student/messages': typeof AuthenticatedDashboardStudentMessagesRoute
  '/_authenticated/dashboard/student/profile': typeof AuthenticatedDashboardStudentProfileRoute
  '/_authenticated/dashboard/admin/': typeof AuthenticatedDashboardAdminIndexRoute
  '/_authenticated/dashboard/client/': typeof AuthenticatedDashboardClientIndexRoute
  '/_authenticated/dashboard/instructor/': typeof AuthenticatedDashboardInstructorIndexRoute
  '/_authenticated/dashboard/student/': typeof AuthenticatedDashboardStudentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/services'
    | '/sitemap.xml'
    | '/solutions'
    | '/dashboard'
    | '/auth/callback'
    | '/auth/reset-password'
    | '/dashboard/assignments'
    | '/dashboard/certificates'
    | '/dashboard/courses'
    | '/dashboard/profile'
    | '/dashboard/requests'
    | '/dashboard/admin/analytics'
    | '/dashboard/admin/announcements'
    | '/dashboard/admin/courses'
    | '/dashboard/admin/messages'
    | '/dashboard/admin/payments'
    | '/dashboard/admin/requests'
    | '/dashboard/admin/settings'
    | '/dashboard/admin/students'
    | '/dashboard/admin/users'
    | '/dashboard/client/announcements'
    | '/dashboard/client/invoices'
    | '/dashboard/client/messages'
    | '/dashboard/client/profile'
    | '/dashboard/client/projects'
    | '/dashboard/client/requests'
    | '/dashboard/instructor/announcements'
    | '/dashboard/instructor/attendance'
    | '/dashboard/instructor/courses'
    | '/dashboard/instructor/messages'
    | '/dashboard/student/announcements'
    | '/dashboard/student/assignments'
    | '/dashboard/student/attendance'
    | '/dashboard/student/certificates'
    | '/dashboard/student/courses'
    | '/dashboard/student/messages'
    | '/dashboard/student/profile'
    | '/dashboard/admin/'
    | '/dashboard/client/'
    | '/dashboard/instructor/'
    | '/dashboard/student/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/services'
    | '/sitemap.xml'
    | '/solutions'
    | '/dashboard'
    | '/auth/callback'
    | '/auth/reset-password'
    | '/dashboard/assignments'
    | '/dashboard/certificates'
    | '/dashboard/courses'
    | '/dashboard/profile'
    | '/dashboard/requests'
    | '/dashboard/admin/analytics'
    | '/dashboard/admin/announcements'
    | '/dashboard/admin/courses'
    | '/dashboard/admin/messages'
    | '/dashboard/admin/payments'
    | '/dashboard/admin/requests'
    | '/dashboard/admin/settings'
    | '/dashboard/admin/students'
    | '/dashboard/admin/users'
    | '/dashboard/client/announcements'
    | '/dashboard/client/invoices'
    | '/dashboard/client/messages'
    | '/dashboard/client/profile'
    | '/dashboard/client/projects'
    | '/dashboard/client/requests'
    | '/dashboard/instructor/announcements'
    | '/dashboard/instructor/attendance'
    | '/dashboard/instructor/courses'
    | '/dashboard/instructor/messages'
    | '/dashboard/student/announcements'
    | '/dashboard/student/assignments'
    | '/dashboard/student/attendance'
    | '/dashboard/student/certificates'
    | '/dashboard/student/courses'
    | '/dashboard/student/messages'
    | '/dashboard/student/profile'
    | '/dashboard/admin'
    | '/dashboard/client'
    | '/dashboard/instructor'
    | '/dashboard/student'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/services'
    | '/sitemap.xml'
    | '/solutions'
    | '/_authenticated/dashboard'
    | '/auth/callback'
    | '/auth/reset-password'
    | '/_authenticated/dashboard/assignments'
    | '/_authenticated/dashboard/certificates'
    | '/_authenticated/dashboard/courses'
    | '/_authenticated/dashboard/profile'
    | '/_authenticated/dashboard/requests'
    | '/_authenticated/dashboard/admin/analytics'
    | '/_authenticated/dashboard/admin/announcements'
    | '/_authenticated/dashboard/admin/courses'
    | '/_authenticated/dashboard/admin/messages'
    | '/_authenticated/dashboard/admin/payments'
    | '/_authenticated/dashboard/admin/requests'
    | '/_authenticated/dashboard/admin/settings'
    | '/_authenticated/dashboard/admin/students'
    | '/_authenticated/dashboard/admin/users'
    | '/_authenticated/dashboard/client/announcements'
    | '/_authenticated/dashboard/client/invoices'
    | '/_authenticated/dashboard/client/messages'
    | '/_authenticated/dashboard/client/profile'
    | '/_authenticated/dashboard/client/projects'
    | '/_authenticated/dashboard/client/requests'
    | '/_authenticated/dashboard/instructor/announcements'
    | '/_authenticated/dashboard/instructor/attendance'
    | '/_authenticated/dashboard/instructor/courses'
    | '/_authenticated/dashboard/instructor/messages'
    | '/_authenticated/dashboard/student/announcements'
    | '/_authenticated/dashboard/student/assignments'
    | '/_authenticated/dashboard/student/attendance'
    | '/_authenticated/dashboard/student/certificates'
    | '/_authenticated/dashboard/student/courses'
    | '/_authenticated/dashboard/student/messages'
    | '/_authenticated/dashboard/student/profile'
    | '/_authenticated/dashboard/admin/'
    | '/_authenticated/dashboard/client/'
    | '/_authenticated/dashboard/instructor/'
    | '/_authenticated/dashboard/student/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRouteWithChildren
  ContactRoute: typeof ContactRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SolutionsRoute: typeof SolutionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/requests': {
      id: '/_authenticated/dashboard/requests'
      path: '/requests'
      fullPath: '/dashboard/requests'
      preLoaderRoute: typeof AuthenticatedDashboardRequestsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/profile': {
      id: '/_authenticated/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof AuthenticatedDashboardProfileRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/courses': {
      id: '/_authenticated/dashboard/courses'
      path: '/courses'
      fullPath: '/dashboard/courses'
      preLoaderRoute: typeof AuthenticatedDashboardCoursesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/certificates': {
      id: '/_authenticated/dashboard/certificates'
      path: '/certificates'
      fullPath: '/dashboard/certificates'
      preLoaderRoute: typeof AuthenticatedDashboardCertificatesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/assignments': {
      id: '/_authenticated/dashboard/assignments'
      path: '/assignments'
      fullPath: '/dashboard/assignments'
      preLoaderRoute: typeof AuthenticatedDashboardAssignmentsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/student/': {
      id: '/_authenticated/dashboard/student/'
      path: '/student'
      fullPath: '/dashboard/student/'
      preLoaderRoute: typeof AuthenticatedDashboardStudentIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/instructor/': {
      id: '/_authenticated/dashboard/instructor/'
      path: '/instructor'
      fullPath: '/dashboard/instructor/'
      preLoaderRoute: typeof AuthenticatedDashboardInstructorIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/client/': {
      id: '/_authenticated/dashboard/client/'
      path: '/client'
      fullPath: '/dashboard/client/'
      preLoaderRoute: typeof AuthenticatedDashboardClientIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/admin/': {
      id: '/_authenticated/dashboard/admin/'
      path: '/admin'
      fullPath: '/dashboard/admin/'
      preLoaderRoute: typeof AuthenticatedDashboardAdminIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/student/profile': {
      id: '/_authenticated/dashboard/student/profile'
      path: '/student/profile'
      fullPath: '/dashboard/student/profile'
      preLoaderRoute: typeof AuthenticatedDashboardStudentProfileRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/student/messages': {
      id: '/_authenticated/dashboard/student/messages'
      path: '/student/messages'
      fullPath: '/dashboard/student/messages'
      preLoaderRoute: typeof AuthenticatedDashboardStudentMessagesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/student/courses': {
      id: '/_authenticated/dashboard/student/courses'
      path: '/student/courses'
      fullPath: '/dashboard/student/courses'
      preLoaderRoute: typeof AuthenticatedDashboardStudentCoursesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/student/certificates': {
      id: '/_authenticated/dashboard/student/certificates'
      path: '/student/certificates'
      fullPath: '/dashboard/student/certificates'
      preLoaderRoute: typeof AuthenticatedDashboardStudentCertificatesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/student/attendance': {
      id: '/_authenticated/dashboard/student/attendance'
      path: '/student/attendance'
      fullPath: '/dashboard/student/attendance'
      preLoaderRoute: typeof AuthenticatedDashboardStudentAttendanceRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/student/assignments': {
      id: '/_authenticated/dashboard/student/assignments'
      path: '/student/assignments'
      fullPath: '/dashboard/student/assignments'
      preLoaderRoute: typeof AuthenticatedDashboardStudentAssignmentsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/student/announcements': {
      id: '/_authenticated/dashboard/student/announcements'
      path: '/student/announcements'
      fullPath: '/dashboard/student/announcements'
      preLoaderRoute: typeof AuthenticatedDashboardStudentAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/instructor/messages': {
      id: '/_authenticated/dashboard/instructor/messages'
      path: '/instructor/messages'
      fullPath: '/dashboard/instructor/messages'
      preLoaderRoute: typeof AuthenticatedDashboardInstructorMessagesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/instructor/courses': {
      id: '/_authenticated/dashboard/instructor/courses'
      path: '/instructor/courses'
      fullPath: '/dashboard/instructor/courses'
      preLoaderRoute: typeof AuthenticatedDashboardInstructorCoursesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/instructor/attendance': {
      id: '/_authenticated/dashboard/instructor/attendance'
      path: '/instructor/attendance'
      fullPath: '/dashboard/instructor/attendance'
      preLoaderRoute: typeof AuthenticatedDashboardInstructorAttendanceRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/instructor/announcements': {
      id: '/_authenticated/dashboard/instructor/announcements'
      path: '/instructor/announcements'
      fullPath: '/dashboard/instructor/announcements'
      preLoaderRoute: typeof AuthenticatedDashboardInstructorAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/client/requests': {
      id: '/_authenticated/dashboard/client/requests'
      path: '/client/requests'
      fullPath: '/dashboard/client/requests'
      preLoaderRoute: typeof AuthenticatedDashboardClientRequestsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/client/projects': {
      id: '/_authenticated/dashboard/client/projects'
      path: '/client/projects'
      fullPath: '/dashboard/client/projects'
      preLoaderRoute: typeof AuthenticatedDashboardClientProjectsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/client/profile': {
      id: '/_authenticated/dashboard/client/profile'
      path: '/client/profile'
      fullPath: '/dashboard/client/profile'
      preLoaderRoute: typeof AuthenticatedDashboardClientProfileRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/client/messages': {
      id: '/_authenticated/dashboard/client/messages'
      path: '/client/messages'
      fullPath: '/dashboard/client/messages'
      preLoaderRoute: typeof AuthenticatedDashboardClientMessagesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/client/invoices': {
      id: '/_authenticated/dashboard/client/invoices'
      path: '/client/invoices'
      fullPath: '/dashboard/client/invoices'
      preLoaderRoute: typeof AuthenticatedDashboardClientInvoicesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/client/announcements': {
      id: '/_authenticated/dashboard/client/announcements'
      path: '/client/announcements'
      fullPath: '/dashboard/client/announcements'
      preLoaderRoute: typeof AuthenticatedDashboardClientAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/admin/users': {
      id: '/_authenticated/dashboard/admin/users'
      path: '/admin/users'
      fullPath: '/dashboard/admin/users'
      preLoaderRoute: typeof AuthenticatedDashboardAdminUsersRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/admin/students': {
      id: '/_authenticated/dashboard/admin/students'
      path: '/admin/students'
      fullPath: '/dashboard/admin/students'
      preLoaderRoute: typeof AuthenticatedDashboardAdminStudentsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/admin/settings': {
      id: '/_authenticated/dashboard/admin/settings'
      path: '/admin/settings'
      fullPath: '/dashboard/admin/settings'
      preLoaderRoute: typeof AuthenticatedDashboardAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/admin/requests': {
      id: '/_authenticated/dashboard/admin/requests'
      path: '/admin/requests'
      fullPath: '/dashboard/admin/requests'
      preLoaderRoute: typeof AuthenticatedDashboardAdminRequestsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/admin/payments': {
      id: '/_authenticated/dashboard/admin/payments'
      path: '/admin/payments'
      fullPath: '/dashboard/admin/payments'
      preLoaderRoute: typeof AuthenticatedDashboardAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/admin/messages': {
      id: '/_authenticated/dashboard/admin/messages'
      path: '/admin/messages'
      fullPath: '/dashboard/admin/messages'
      preLoaderRoute: typeof AuthenticatedDashboardAdminMessagesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/admin/courses': {
      id: '/_authenticated/dashboard/admin/courses'
      path: '/admin/courses'
      fullPath: '/dashboard/admin/courses'
      preLoaderRoute: typeof AuthenticatedDashboardAdminCoursesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/admin/announcements': {
      id: '/_authenticated/dashboard/admin/announcements'
      path: '/admin/announcements'
      fullPath: '/dashboard/admin/announcements'
      preLoaderRoute: typeof AuthenticatedDashboardAdminAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/admin/analytics': {
      id: '/_authenticated/dashboard/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/dashboard/admin/analytics'
      preLoaderRoute: typeof AuthenticatedDashboardAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardAssignmentsRoute: typeof AuthenticatedDashboardAssignmentsRoute
  AuthenticatedDashboardCertificatesRoute: typeof AuthenticatedDashboardCertificatesRoute
  AuthenticatedDashboardCoursesRoute: typeof AuthenticatedDashboardCoursesRoute
  AuthenticatedDashboardProfileRoute: typeof AuthenticatedDashboardProfileRoute
  AuthenticatedDashboardRequestsRoute: typeof AuthenticatedDashboardRequestsRoute
  AuthenticatedDashboardAdminAnalyticsRoute: typeof AuthenticatedDashboardAdminAnalyticsRoute
  AuthenticatedDashboardAdminAnnouncementsRoute: typeof AuthenticatedDashboardAdminAnnouncementsRoute
  AuthenticatedDashboardAdminCoursesRoute: typeof AuthenticatedDashboardAdminCoursesRoute
  AuthenticatedDashboardAdminMessagesRoute: typeof AuthenticatedDashboardAdminMessagesRoute
  AuthenticatedDashboardAdminPaymentsRoute: typeof AuthenticatedDashboardAdminPaymentsRoute
  AuthenticatedDashboardAdminRequestsRoute: typeof AuthenticatedDashboardAdminRequestsRoute
  AuthenticatedDashboardAdminSettingsRoute: typeof AuthenticatedDashboardAdminSettingsRoute
  AuthenticatedDashboardAdminStudentsRoute: typeof AuthenticatedDashboardAdminStudentsRoute
  AuthenticatedDashboardAdminUsersRoute: typeof AuthenticatedDashboardAdminUsersRoute
  AuthenticatedDashboardClientAnnouncementsRoute: typeof AuthenticatedDashboardClientAnnouncementsRoute
  AuthenticatedDashboardClientInvoicesRoute: typeof AuthenticatedDashboardClientInvoicesRoute
  AuthenticatedDashboardClientMessagesRoute: typeof AuthenticatedDashboardClientMessagesRoute
  AuthenticatedDashboardClientProfileRoute: typeof AuthenticatedDashboardClientProfileRoute
  AuthenticatedDashboardClientProjectsRoute: typeof AuthenticatedDashboardClientProjectsRoute
  AuthenticatedDashboardClientRequestsRoute: typeof AuthenticatedDashboardClientRequestsRoute
  AuthenticatedDashboardInstructorAnnouncementsRoute: typeof AuthenticatedDashboardInstructorAnnouncementsRoute
  AuthenticatedDashboardInstructorAttendanceRoute: typeof AuthenticatedDashboardInstructorAttendanceRoute
  AuthenticatedDashboardInstructorCoursesRoute: typeof AuthenticatedDashboardInstructorCoursesRoute
  AuthenticatedDashboardInstructorMessagesRoute: typeof AuthenticatedDashboardInstructorMessagesRoute
  AuthenticatedDashboardStudentAnnouncementsRoute: typeof AuthenticatedDashboardStudentAnnouncementsRoute
  AuthenticatedDashboardStudentAssignmentsRoute: typeof AuthenticatedDashboardStudentAssignmentsRoute
  AuthenticatedDashboardStudentAttendanceRoute: typeof AuthenticatedDashboardStudentAttendanceRoute
  AuthenticatedDashboardStudentCertificatesRoute: typeof AuthenticatedDashboardStudentCertificatesRoute
  AuthenticatedDashboardStudentCoursesRoute: typeof AuthenticatedDashboardStudentCoursesRoute
  AuthenticatedDashboardStudentMessagesRoute: typeof AuthenticatedDashboardStudentMessagesRoute
  AuthenticatedDashboardStudentProfileRoute: typeof AuthenticatedDashboardStudentProfileRoute
  AuthenticatedDashboardAdminIndexRoute: typeof AuthenticatedDashboardAdminIndexRoute
  AuthenticatedDashboardClientIndexRoute: typeof AuthenticatedDashboardClientIndexRoute
  AuthenticatedDashboardInstructorIndexRoute: typeof AuthenticatedDashboardInstructorIndexRoute
  AuthenticatedDashboardStudentIndexRoute: typeof AuthenticatedDashboardStudentIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardAssignmentsRoute:
      AuthenticatedDashboardAssignmentsRoute,
    AuthenticatedDashboardCertificatesRoute:
      AuthenticatedDashboardCertificatesRoute,
    AuthenticatedDashboardCoursesRoute: AuthenticatedDashboardCoursesRoute,
    AuthenticatedDashboardProfileRoute: AuthenticatedDashboardProfileRoute,
    AuthenticatedDashboardRequestsRoute: AuthenticatedDashboardRequestsRoute,
    AuthenticatedDashboardAdminAnalyticsRoute:
      AuthenticatedDashboardAdminAnalyticsRoute,
    AuthenticatedDashboardAdminAnnouncementsRoute:
      AuthenticatedDashboardAdminAnnouncementsRoute,
    AuthenticatedDashboardAdminCoursesRoute:
      AuthenticatedDashboardAdminCoursesRoute,
    AuthenticatedDashboardAdminMessagesRoute:
      AuthenticatedDashboardAdminMessagesRoute,
    AuthenticatedDashboardAdminPaymentsRoute:
      AuthenticatedDashboardAdminPaymentsRoute,
    AuthenticatedDashboardAdminRequestsRoute:
      AuthenticatedDashboardAdminRequestsRoute,
    AuthenticatedDashboardAdminSettingsRoute:
      AuthenticatedDashboardAdminSettingsRoute,
    AuthenticatedDashboardAdminStudentsRoute:
      AuthenticatedDashboardAdminStudentsRoute,
    AuthenticatedDashboardAdminUsersRoute:
      AuthenticatedDashboardAdminUsersRoute,
    AuthenticatedDashboardClientAnnouncementsRoute:
      AuthenticatedDashboardClientAnnouncementsRoute,
    AuthenticatedDashboardClientInvoicesRoute:
      AuthenticatedDashboardClientInvoicesRoute,
    AuthenticatedDashboardClientMessagesRoute:
      AuthenticatedDashboardClientMessagesRoute,
    AuthenticatedDashboardClientProfileRoute:
      AuthenticatedDashboardClientProfileRoute,
    AuthenticatedDashboardClientProjectsRoute:
      AuthenticatedDashboardClientProjectsRoute,
    AuthenticatedDashboardClientRequestsRoute:
      AuthenticatedDashboardClientRequestsRoute,
    AuthenticatedDashboardInstructorAnnouncementsRoute:
      AuthenticatedDashboardInstructorAnnouncementsRoute,
    AuthenticatedDashboardInstructorAttendanceRoute:
      AuthenticatedDashboardInstructorAttendanceRoute,
    AuthenticatedDashboardInstructorCoursesRoute:
      AuthenticatedDashboardInstructorCoursesRoute,
    AuthenticatedDashboardInstructorMessagesRoute:
      AuthenticatedDashboardInstructorMessagesRoute,
    AuthenticatedDashboardStudentAnnouncementsRoute:
      AuthenticatedDashboardStudentAnnouncementsRoute,
    AuthenticatedDashboardStudentAssignmentsRoute:
      AuthenticatedDashboardStudentAssignmentsRoute,
    AuthenticatedDashboardStudentAttendanceRoute:
      AuthenticatedDashboardStudentAttendanceRoute,
    AuthenticatedDashboardStudentCertificatesRoute:
      AuthenticatedDashboardStudentCertificatesRoute,
    AuthenticatedDashboardStudentCoursesRoute:
      AuthenticatedDashboardStudentCoursesRoute,
    AuthenticatedDashboardStudentMessagesRoute:
      AuthenticatedDashboardStudentMessagesRoute,
    AuthenticatedDashboardStudentProfileRoute:
      AuthenticatedDashboardStudentProfileRoute,
    AuthenticatedDashboardAdminIndexRoute:
      AuthenticatedDashboardAdminIndexRoute,
    AuthenticatedDashboardClientIndexRoute:
      AuthenticatedDashboardClientIndexRoute,
    AuthenticatedDashboardInstructorIndexRoute:
      AuthenticatedDashboardInstructorIndexRoute,
    AuthenticatedDashboardStudentIndexRoute:
      AuthenticatedDashboardStudentIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRouteWithChildren,
  ContactRoute: ContactRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SolutionsRoute: SolutionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
