/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDashboardRequestsRouteImport } from './routes/_authenticated/dashboard.requests'
import { Route as AuthenticatedDashboardProfileRouteImport } from './routes/_authenticated/dashboard.profile'
import { Route as AuthenticatedDashboardCoursesRouteImport } from './routes/_authenticated/dashboard.courses'
import { Route as AuthenticatedDashboardCertificatesRouteImport } from './routes/_authenticated/dashboard.certificates'
import { Route as AuthenticatedDashboardAssignmentsRouteImport } from './routes/_authenticated/dashboard.assignments'
import { Route as AuthenticatedDashboardAdminStudentsRouteImport } from './routes/_authenticated/dashboard.admin.students'
import { Route as AuthenticatedDashboardAdminSettingsRouteImport } from './routes/_authenticated/dashboard.admin.settings'
import { Route as AuthenticatedDashboardAdminRequestsRouteImport } from './routes/_authenticated/dashboard.admin.requests'
import { Route as AuthenticatedDashboardAdminPaymentsRouteImport } from './routes/_authenticated/dashboard.admin.payments'
import { Route as AuthenticatedDashboardAdminCoursesRouteImport } from './routes/_authenticated/dashboard.admin.courses'

const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRequestsRoute =
  AuthenticatedDashboardRequestsRouteImport.update({
    id: '/requests',
    path: '/requests',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardProfileRoute =
  AuthenticatedDashboardProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardCoursesRoute =
  AuthenticatedDashboardCoursesRouteImport.update({
    id: '/courses',
    path: '/courses',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardCertificatesRoute =
  AuthenticatedDashboardCertificatesRouteImport.update({
    id: '/certificates',
    path: '/certificates',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAssignmentsRoute =
  AuthenticatedDashboardAssignmentsRouteImport.update({
    id: '/assignments',
    path: '/assignments',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAdminStudentsRoute =
  AuthenticatedDashboardAdminStudentsRouteImport.update({
    id: '/admin/students',
    path: '/admin/students',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAdminSettingsRoute =
  AuthenticatedDashboardAdminSettingsRouteImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAdminRequestsRoute =
  AuthenticatedDashboardAdminRequestsRouteImport.update({
    id: '/admin/requests',
    path: '/admin/requests',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAdminPaymentsRoute =
  AuthenticatedDashboardAdminPaymentsRouteImport.update({
    id: '/admin/payments',
    path: '/admin/payments',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAdminCoursesRoute =
  AuthenticatedDashboardAdminCoursesRouteImport.update({
    id: '/admin/courses',
    path: '/admin/courses',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solutions': typeof SolutionsRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/assignments': typeof AuthenticatedDashboardAssignmentsRoute
  '/dashboard/certificates': typeof AuthenticatedDashboardCertificatesRoute
  '/dashboard/courses': typeof AuthenticatedDashboardCoursesRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/dashboard/requests': typeof AuthenticatedDashboardRequestsRoute
  '/dashboard/admin/courses': typeof AuthenticatedDashboardAdminCoursesRoute
  '/dashboard/admin/payments': typeof AuthenticatedDashboardAdminPaymentsRoute
  '/dashboard/admin/requests': typeof AuthenticatedDashboardAdminRequestsRoute
  '/dashboard/admin/settings': typeof AuthenticatedDashboardAdminSettingsRoute
  '/dashboard/admin/students': typeof AuthenticatedDashboardAdminStudentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solutions': typeof SolutionsRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/assignments': typeof AuthenticatedDashboardAssignmentsRoute
  '/dashboard/certificates': typeof AuthenticatedDashboardCertificatesRoute
  '/dashboard/courses': typeof AuthenticatedDashboardCoursesRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/dashboard/requests': typeof AuthenticatedDashboardRequestsRoute
  '/dashboard/admin/courses': typeof AuthenticatedDashboardAdminCoursesRoute
  '/dashboard/admin/payments': typeof AuthenticatedDashboardAdminPaymentsRoute
  '/dashboard/admin/requests': typeof AuthenticatedDashboardAdminRequestsRoute
  '/dashboard/admin/settings': typeof AuthenticatedDashboardAdminSettingsRoute
  '/dashboard/admin/students': typeof AuthenticatedDashboardAdminStudentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solutions': typeof SolutionsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/dashboard/assignments': typeof AuthenticatedDashboardAssignmentsRoute
  '/_authenticated/dashboard/certificates': typeof AuthenticatedDashboardCertificatesRoute
  '/_authenticated/dashboard/courses': typeof AuthenticatedDashboardCoursesRoute
  '/_authenticated/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/_authenticated/dashboard/requests': typeof AuthenticatedDashboardRequestsRoute
  '/_authenticated/dashboard/admin/courses': typeof AuthenticatedDashboardAdminCoursesRoute
  '/_authenticated/dashboard/admin/payments': typeof AuthenticatedDashboardAdminPaymentsRoute
  '/_authenticated/dashboard/admin/requests': typeof AuthenticatedDashboardAdminRequestsRoute
  '/_authenticated/dashboard/admin/settings': typeof AuthenticatedDashboardAdminSettingsRoute
  '/_authenticated/dashboard/admin/students': typeof AuthenticatedDashboardAdminStudentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/services'
    | '/sitemap.xml'
    | '/solutions'
    | '/dashboard'
    | '/auth/callback'
    | '/dashboard/assignments'
    | '/dashboard/certificates'
    | '/dashboard/courses'
    | '/dashboard/profile'
    | '/dashboard/requests'
    | '/dashboard/admin/courses'
    | '/dashboard/admin/payments'
    | '/dashboard/admin/requests'
    | '/dashboard/admin/settings'
    | '/dashboard/admin/students'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/services'
    | '/sitemap.xml'
    | '/solutions'
    | '/dashboard'
    | '/auth/callback'
    | '/dashboard/assignments'
    | '/dashboard/certificates'
    | '/dashboard/courses'
    | '/dashboard/profile'
    | '/dashboard/requests'
    | '/dashboard/admin/courses'
    | '/dashboard/admin/payments'
    | '/dashboard/admin/requests'
    | '/dashboard/admin/settings'
    | '/dashboard/admin/students'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/services'
    | '/sitemap.xml'
    | '/solutions'
    | '/_authenticated/dashboard'
    | '/auth/callback'
    | '/_authenticated/dashboard/assignments'
    | '/_authenticated/dashboard/certificates'
    | '/_authenticated/dashboard/courses'
    | '/_authenticated/dashboard/profile'
    | '/_authenticated/dashboard/requests'
    | '/_authenticated/dashboard/admin/courses'
    | '/_authenticated/dashboard/admin/payments'
    | '/_authenticated/dashboard/admin/requests'
    | '/_authenticated/dashboard/admin/settings'
    | '/_authenticated/dashboard/admin/students'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRouteWithChildren
  ContactRoute: typeof ContactRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SolutionsRoute: typeof SolutionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/requests': {
      id: '/_authenticated/dashboard/requests'
      path: '/requests'
      fullPath: '/dashboard/requests'
      preLoaderRoute: typeof AuthenticatedDashboardRequestsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/profile': {
      id: '/_authenticated/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof AuthenticatedDashboardProfileRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/courses': {
      id: '/_authenticated/dashboard/courses'
      path: '/courses'
      fullPath: '/dashboard/courses'
      preLoaderRoute: typeof AuthenticatedDashboardCoursesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/certificates': {
      id: '/_authenticated/dashboard/certificates'
      path: '/certificates'
      fullPath: '/dashboard/certificates'
      preLoaderRoute: typeof AuthenticatedDashboardCertificatesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/assignments': {
      id: '/_authenticated/dashboard/assignments'
      path: '/assignments'
      fullPath: '/dashboard/assignments'
      preLoaderRoute: typeof AuthenticatedDashboardAssignmentsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/admin/students': {
      id: '/_authenticated/dashboard/admin/students'
      path: '/admin/students'
      fullPath: '/dashboard/admin/students'
      preLoaderRoute: typeof AuthenticatedDashboardAdminStudentsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/admin/settings': {
      id: '/_authenticated/dashboard/admin/settings'
      path: '/admin/settings'
      fullPath: '/dashboard/admin/settings'
      preLoaderRoute: typeof AuthenticatedDashboardAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/admin/requests': {
      id: '/_authenticated/dashboard/admin/requests'
      path: '/admin/requests'
      fullPath: '/dashboard/admin/requests'
      preLoaderRoute: typeof AuthenticatedDashboardAdminRequestsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/admin/payments': {
      id: '/_authenticated/dashboard/admin/payments'
      path: '/admin/payments'
      fullPath: '/dashboard/admin/payments'
      preLoaderRoute: typeof AuthenticatedDashboardAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/admin/courses': {
      id: '/_authenticated/dashboard/admin/courses'
      path: '/admin/courses'
      fullPath: '/dashboard/admin/courses'
      preLoaderRoute: typeof AuthenticatedDashboardAdminCoursesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardAssignmentsRoute: typeof AuthenticatedDashboardAssignmentsRoute
  AuthenticatedDashboardCertificatesRoute: typeof AuthenticatedDashboardCertificatesRoute
  AuthenticatedDashboardCoursesRoute: typeof AuthenticatedDashboardCoursesRoute
  AuthenticatedDashboardProfileRoute: typeof AuthenticatedDashboardProfileRoute
  AuthenticatedDashboardRequestsRoute: typeof AuthenticatedDashboardRequestsRoute
  AuthenticatedDashboardAdminCoursesRoute: typeof AuthenticatedDashboardAdminCoursesRoute
  AuthenticatedDashboardAdminPaymentsRoute: typeof AuthenticatedDashboardAdminPaymentsRoute
  AuthenticatedDashboardAdminRequestsRoute: typeof AuthenticatedDashboardAdminRequestsRoute
  AuthenticatedDashboardAdminSettingsRoute: typeof AuthenticatedDashboardAdminSettingsRoute
  AuthenticatedDashboardAdminStudentsRoute: typeof AuthenticatedDashboardAdminStudentsRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardAssignmentsRoute:
      AuthenticatedDashboardAssignmentsRoute,
    AuthenticatedDashboardCertificatesRoute:
      AuthenticatedDashboardCertificatesRoute,
    AuthenticatedDashboardCoursesRoute: AuthenticatedDashboardCoursesRoute,
    AuthenticatedDashboardProfileRoute: AuthenticatedDashboardProfileRoute,
    AuthenticatedDashboardRequestsRoute: AuthenticatedDashboardRequestsRoute,
    AuthenticatedDashboardAdminCoursesRoute:
      AuthenticatedDashboardAdminCoursesRoute,
    AuthenticatedDashboardAdminPaymentsRoute:
      AuthenticatedDashboardAdminPaymentsRoute,
    AuthenticatedDashboardAdminRequestsRoute:
      AuthenticatedDashboardAdminRequestsRoute,
    AuthenticatedDashboardAdminSettingsRoute:
      AuthenticatedDashboardAdminSettingsRoute,
    AuthenticatedDashboardAdminStudentsRoute:
      AuthenticatedDashboardAdminStudentsRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRouteWithChildren,
  ContactRoute: ContactRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SolutionsRoute: SolutionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
